language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo64-8.0
  - Pharo64-7.0
  - Pharo32-7.0
  - Pharo-6.1  
  - Pharo64-6.1
  
 matrix:
  allow_failures:
  - smalltalk: Pharo64-8.0
  - smalltalk: Pharo-6.1 
  - smalltalk: Pharo64-6.1
  fast_finish: true