language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo32-6.1 
  - Pharo64-6.1
  - Pharo64-7.0
  - Pharo32-7.0
matrix:
  allow_failures:
  - smalltalk: Pharo64-7.0
  - smalltalk: Pharo32-7.0
fast_finish: true

  
